import React from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Menu from '../components/Menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Alimoudine IDRISSOU Portfolio',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="en">
    <body className={`${inter.className} h-screen flex flex-col md:flex-row bg-gray-50`}>
      <aside className="w-full md:w-1/4 p-8 bg-white border-r border-gray-200 shadow-lg flex flex-col justify-between">
        <Menu />
      </aside>
      <main className="flex-1 p-8 bg-gray-100 overflow-y-auto">
        {children}
      </main>
    </body>
  </html>
);

export default RootLayout;
