// src/app/layout.tsx
import React from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { LayoutWrapper } from '../components/LayoutWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Alimoudine IDRISSOU Portfolio',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="en" className={inter.className}>
    <head>
      {/* Netlify Widget */}
      <script async src="https://identity.netlify.com/v1/netlify-identity-widget.js" />
    </head>
    <body>
      <LayoutWrapper>
        {children}
      </LayoutWrapper>
    </body>
  </html>
);

export default RootLayout;